version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/python/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "pip"
    directory: "/uv/helpers"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "16:00"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]