site_name: strongtyping
nav:
    - Home: 'index.md'
    - User's guide:
        - 'Installation': 'install.md'
    - Reference:
        - 'match_typing': 'match_typing.md'
        - 'match_class_typing': 'match_class_typing.md'
        - 'severity_level': 'match_class_typing.md'
        - 'typed_namedtuple': 'namedtuple.md'
        - 'getter': 'getter_setter.md'
        - 'setter': 'getter_setter.md'
        - 'getter_setter': 'getter_setter.md'
        - 'rest_docs_from_typing': 'docs_from_typing.md'
        - 'numpy_docs_from_typing': 'docs_from_typing.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
theme: readthedocs
