from typing import Any

from strongtyping.strong_typing import match_typing as match_typing

def action(f: Any, frefs: Any) -> Any: ...
def getter(f: Any) -> Any: ...
def setter(f: Any) -> Any: ...
def deleter(f: Any) -> Any: ...
def documenter(f: Any) -> Any: ...
def getter_setter(f: Any) -> Any: ...
