from strongtyping.exceptions import TypeMismatch as TypeMismatch, ValidationError as ValidationError
from strongtyping.strong_typing import match_typing as match_typing
from typing import Any, Callable, Sized, TypeVar

T = TypeVar('T')

def validate_typed_dict(base: type[Any], /, data: dict[Any, Any]) -> bool: ...
def Gt(limit: int, /) -> Callable[[int], bool]: ...
def Gte(limit: int, /) -> Callable[[int], bool]: ...
def Lt(limit: int, /) -> Callable[[int], bool]: ...
def Lte(limit: int, /) -> Callable[[int], bool]: ...
def Range(lower: int, upper: int, /) -> Callable[[int], bool]: ...
def IsPositive() -> Callable[[int], bool]: ...
def IsNegative() -> Callable[[int], bool]: ...
def IsUUid() -> Callable[[str], bool]: ...
def Len(*, lower: int, upper: int | None = None) -> Callable[[Sized], bool]: ...
def Regex(regex: str, /) -> Callable[[str], bool]: ...
