import weakref
from typing import Any, _GenericAlias, _SpecialForm

from _typeshed import Incomplete

class _Validator(_GenericAlias, _root=True):
    def __getitem__(self, item: Any) -> Any: ...
    def __hash__(self) -> int: ...

class _IterValidator(_GenericAlias, _root=True):
    def __getitem__(self, item: Any) -> Any: ...
    def __hash__(self) -> int: ...

@_SpecialForm
def Validator(self, parameters: Any, *args: Any, **kwargs: Any) -> Any: ...
@_SpecialForm
def IterValidator(self, parameters: Any, *args: Any, **kwargs: Any) -> Any: ...

class FrozenType:
    weakref: weakref.WeakKeyDictionary[object, Any]
    required_type: Incomplete
    stored_value: Incomplete
    def __init__(self, required_type: Any, stored_value: Any = None) -> None: ...
    def __get__(self, instance: object = None, owner: type[Any] | None = None) -> Any: ...
    def __set__(self, instance: object = None, value: Any = None) -> None: ...
    def get_doc(self) -> str | None: ...
    @classmethod
    def cast(cls, instance: Any, origin: Any, new: Any) -> tuple[FrozenType, Any, object]: ...
    def error_msg(self, value: Any, attribute_name: str = "This") -> Exception: ...
