from collections.abc import Callable
from queue import Queue
from typing import Any, TypeVar

from _typeshed import Incomplete

from strongtyping._utils import ORIGINAL_DUCK_TYPES as ORIGINAL_DUCK_TYPES
from strongtyping.exceptions import ValidationError as ValidationError

empty: Incomplete
default_return_queue: Queue[Any]
T = TypeVar("T")
typing_base_class: Incomplete

def get_possible_types(typ_to_check: Any, origin_name: str = "") -> Any: ...
def get_origins(typ_to_check: Any) -> tuple[Any, str]: ...
def checking_typing_dict(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_set(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_type(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_union(arg: Any, possible_types: Any, mro: bool, **kwargs: Any) -> bool: ...
def checking_typing_optional(arg: Any, possible_types: Any, mro: bool, **kwargs: Any) -> bool: ...
def checking_typing_iterator(arg: object, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_callable(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_tuple(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_list(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_ellipsis(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_json(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_generator(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_literal(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_validator(
    arg: Any, possible_types: Any, *args: Any, **kwargs: Any
) -> bool | None: ...
def checking_typing_itervalidator(
    arg: Any, possible_types: Any, *args: Any, **kwargs: Any
) -> bool: ...
def checking_typing_iterable(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_typedict_values(
    args: dict[Any, Any], required_types: dict[Any, Any], total: bool
) -> bool: ...
def checking_typing_class(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_typeddict(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def checking_typing_typeddict_required(
    arg: Any, possible_types: Any, *args: Any, **kwargs: Any
) -> bool: ...
def checking_typing_typeddict_notrequired(
    arg: Any, possible_types: Any, *args: Any, **kwargs: Any
) -> bool: ...
def checking_typing_unpack(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def validate_object(value: Any, validation_func: Callable[[Any], bool] | None = None) -> bool: ...
def check_duck_typing(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...
def check_typevar(arg: Any, possible_types: Any, *args: Any, **kwargs: Any) -> bool: ...

supported_typings: Incomplete

def check_annotated_type(argument: Any, type_of: Any) -> bool: ...
def check_type(argument: Any, type_of: Any, mro: bool = False, **kwargs: Any) -> Any: ...
