from _typeshed import Incomplete
from strongtyping._utils import (
    action as action,
    get_severity_level as get_severity_level,
    remove_subclass as remove_subclass,
)
from strongtyping.cached_set import CachedSet as CachedSet
from strongtyping.config import SEVERITY_LEVEL as SEVERITY_LEVEL
from strongtyping.exceptions import TypeMismatch as TypeMismatch, UndefinedKey as UndefinedKey
from strongtyping.strong_typing_utils import (
    check_type as check_type,
    checking_typing_typedict_values as checking_typing_typedict_values,
    default_return_queue as default_return_queue,
    get_origins as get_origins,
)
from typing import Any, Callable

CACHE_IGNORE_CLASS_FUNCTIONS: Incomplete

def match_typing(
    _func: Callable[..., Any] | None = None,
    *,
    excep_raise: type[Exception] = ...,
    subclass: bool = False,
    severity: str = "env",
    **kwargs: Any,
) -> Any: ...
def add_required_methods_to_class(cls, inst: Any) -> None: ...

class MatchTypedDict:
    def __new__(cls, instance: type[Any] | None = None, *args: Any, **kwargs: Any) -> Any: ...
    excep_raise: type[Exception]
    cache_size: int
    severity: str
    cls: Any
    __annotations__: Incomplete
    __total__: Incomplete
    def __init__(self, cls: type[Any] | None = None, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, item: str) -> Any: ...
    @property
    def is_typed_dict(self) -> bool: ...
    def __match_class_repr__(self) -> str: ...
    def create_error_msg(self, args: Any) -> str: ...
    def check_annotations(self) -> bool: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...

def match_class_typing(cls=None, **kwargs: Any) -> Any: ...
def getter(func: Any = None) -> Any: ...
def setter(func: Any = None) -> Any: ...
def getter_setter(func: Any = None) -> Any: ...

class FinalClass:
    cls: Any
    def __new__(cls, instance: type[Any] | None = None, *args: Any, **kwargs: Any) -> Any: ...
    __doc__: Incomplete
    def __init__(self, cls: type[Any] | None = None, *args: Any, **kwargs: Any) -> None: ...
    def __getattr__(self, item: str) -> Any: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
    def get_doc(self) -> str: ...
