from _typeshed import Incomplete
from strongtyping._utils import action as action, remove_subclass as remove_subclass
from strongtyping.cached_set import CachedSet as CachedSet
from strongtyping.config import SEVERITY_LEVEL as SEVERITY_LEVEL
from strongtyping.strong_typing_utils import TypeMismatch as TypeMismatch, check_type as check_type, checking_typing_typedict_values as checking_typing_typedict_values, default_return_queue as default_return_queue
from typing import Any, Type, TypeVar
T = TypeVar('T')

CACHE_IGNORE_CLASS_FUNCTIONS: Incomplete

def _raise_error_or_warning(msg: str, failed_params: tuple[str, ...], annotated_values: dict[str, Any], annotations: str, excep_raise: Type[Exception] = ..., severity_level: Incomplete = ...) -> None: ...
def match_typing(_func: Incomplete | None = ..., *, excep_raise: Type[Exception] = ..., subclass: bool = ..., severity: str = ..., **kwargs: Any): ...
def add_required_methods_to_class(cls, inst) -> None: ...

class MatchTypedDict:
    excep_raise: Incomplete
    cache_size: Incomplete
    severity: Incomplete
    cls: Incomplete
    def __new__(cls, instance: Incomplete | None = ..., *args, **kwargs): ...
    def __init__(self, cls: Incomplete | None = ..., *args, **kwargs) -> None: ...
    def __getattr__(self, item): ...
    @property
    def is_typed_dict(self): ...
    def __match_class_repr__(self): ...
    def create_error_msg(self, args: dict): ...
    def _no_required_inside(self, val): ...
    def check_annotations(self): ...
    def __call__(self, *args, **kwargs): ...

def match_class_typing(cls: Type[T] | None = ..., **kwargs: Any): ...
def getter(func: Incomplete | None = ...): ...
def setter(func: Incomplete | None = ...): ...
def getter_setter(func: Incomplete | None = ...): ...

class FinalClass:
    cls: Incomplete
    def __new__(cls, instance: Incomplete | None = ..., *args, **kwargs): ...
    def __init__(self, cls: Incomplete | None = ..., *args, **kwargs) -> None: ...
    def __getattr__(self, item): ...
    def __call__(self, *args, **kwargs): ...
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    @property
    def __doc__(self): ...
