from typing import Any

def rest_docs_from_typing(_func: Any=..., *, insert_at: str=..., remove_linebreak: bool=...) -> Any: ...
def numpy_docs_from_typing(_func: Any=..., *, insert_at: str=..., remove_linebreak: bool=...) -> Any: ...
