# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov isort black
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Check with isort
        run: isort strongtyping --check-only
      - name: Lint with black
        run: python -m black strongtyping --check
      - name: Test with pytest
        run: |
          pytest strongtyping --cov=strongtyping
      - name: Run coverage
        run: |
          codecov --token=${{ secrets.CODECOV_TOKEN }}
