from typing import Any, Union

class CachedDict(dict):
    memory_limit: Any = ...
    def __init__(
        self, memory_limit: Union[int, float] = ..., *args: Any, **kwargs: Any
    ) -> None: ...
    def __setitem__(self, key: Any, value: Any) -> Any: ...
