from strongtyping.strong_typing_utils import get_origins as get_origins, get_possible_types as get_possible_types
from typing import Any

Pattern: Any

def getsource(object: Any): ...

ARGUMENT_TYPE: Any

def union_types(val: Any, type_origins: Any): ...
def get_type_info(val: Any, type_origins: Any): ...
def docs_from_typing_numpy_format(annotations: Any, additional_infos: Any, func_params: Any, remove_linebreak: Any, func_info: Any): ...
def docs_from_typing_reST_format(annotations: Any, additional_infos: Any, func_params: Any, remove_linebreak: Any, func_info: Any): ...
def docs_from_typing(func: Any, remove_linebreak: Any, style: Any): ...
def rest_docs_from_typing(_func: Any=..., *, insert_at: str=..., remove_linebreak: bool=...) -> Any: ...
def numpy_docs_from_typing(_func: Any=..., *, insert_at: str=..., remove_linebreak: bool=...) -> Any: ...
def class_docs_from_typing(_cls: Any=..., *, doc_type: str=...) -> Any:
